using System;
using System.Collections.Generic;
using System.Linq;
using Write2Congress.Shared.BusinessLayer;
using Write2Congress.Shared.DomainModel.Interface;
using static Write2Congress.Shared.DomainModel.ApiModels.ProPublica.BaseResult;

namespace Write2Congress.Shared.DomainModel.ApiModels.ProPublica
{
    public class SingleLegislatorResult
    {
        public static List<ICommittee> GetLegislatorsCommittees(SingleLegislatorResult.Rootobject result)
        {
            if (result == null || result.results == null || result.results.Length < 1 
                || result.results[0].roles == null || result.results[0].roles.Length < 1)
                return null;

            Role lastestRole;

            try
            {
                lastestRole = result.results[0].roles.OrderByDescending(r => Convert.ToInt32(r.congress)).FirstOrDefault();
            }
            catch
            {
				lastestRole = result.results[0].roles.FirstOrDefault();
                //var lastestRole1 = result.results[0].roles.OrderBy(r => Convert.ToInt32(r.congress)).FirstOrDefault();
            }

            if (lastestRole?.committees == null && lastestRole?.subcommittees == null)
                return null;

            var committees = new List<ICommittee>();

            foreach(var committee in lastestRole.committees)
            {
                var newCommittee = new Write2Congress.Shared.DomainModel.Committee()
                {
                    Id = committee.code ?? string.Empty,
                    Chamber = DataTransformationUtil.LegislativeBodyFromSunlight(lastestRole.chamber),
                    IsSubcommittee = false,
                    Name = committee.name ?? string.Empty,
                    ParentCommitteeId = string.Empty,
                    Phone = string.Empty,
                    Url = string.Empty
                };

                committees.Add((ICommittee)newCommittee);
            }

            foreach(var subCommittee in lastestRole.subcommittees)
            {
                var newCommittee = new Write2Congress.Shared.DomainModel.Committee()
                {
                    Id = subCommittee.code ?? string.Empty,
                    Chamber = DataTransformationUtil.LegislativeBodyFromSunlight(lastestRole.chamber),
                    IsSubcommittee = true,
                    Name = subCommittee.name ?? string.Empty,
                    ParentCommitteeId = subCommittee.parent_committee_id ?? string.Empty,
                    Phone = string.Empty,
                    Url = string.Empty
                };

                committees.Add((ICommittee)newCommittee);                
            }


            return committees;
        }


        #region JsonToCsharp AutoGenerated code
        public class Rootobject : BaseRootObject, IServiceResult<ICommittee>
        {
            public Result[] results { get; set; }

            List<ICommittee> IServiceResult<ICommittee>.GetResults()
            {
                return GetLegislatorsCommittees(this);
            }
        }

        public class Result
        {
            public string member_id { get; set; }
            public string first_name { get; set; }
            public string middle_name { get; set; }
            public string last_name { get; set; }
            public string suffix { get; set; }
            public string date_of_birth { get; set; }
            public string gender { get; set; }
            public string url { get; set; }
            public string times_topics_url { get; set; }
            public string times_tag { get; set; }
            public string govtrack_id { get; set; }
            public string cspan_id { get; set; }
            public string votesmart_id { get; set; }
            public string icpsr_id { get; set; }
            public string twitter_account { get; set; }
            public string facebook_account { get; set; }
            public string youtube_account { get; set; }
            public string crp_id { get; set; }
            public string google_entity_id { get; set; }
            public string rss_url { get; set; }
            public bool in_office { get; set; }
            public string current_party { get; set; }
            public string most_recent_vote { get; set; }
            public Role[] roles { get; set; }
        }

        public class Role
        {
            public string congress { get; set; }
            public string chamber { get; set; }
            public string title { get; set; }
            public string short_title { get; set; }
            public string state { get; set; }
            public string party { get; set; }
            public string leadership_role { get; set; }
            public string fec_candidate_id { get; set; }
            public string seniority { get; set; }
            public string district { get; set; }
            public bool at_large { get; set; }
            public string ocd_id { get; set; }
            public string start_date { get; set; }
            public string end_date { get; set; }
            public string office { get; set; }
            public string phone { get; set; }
            public string fax { get; set; }
            public string contact_form { get; set; }
            public int? bills_sponsored { get; set; }
            public int? bills_cosponsored { get; set; }
            public float? missed_votes_pct { get; set; }
            public float? votes_with_party_pct { get; set; }
            public Committee[] committees { get; set; }
            public Subcommittee[] subcommittees { get; set; }
        }

        public class Committee
        {
            public string name { get; set; }
            public string code { get; set; }
            public string api_uri { get; set; }
            public string side { get; set; }
            public string title { get; set; }
            public int? rank_in_party { get; set; }
            public string begin_date { get; set; }
            public string end_date { get; set; }
        }

        public class Subcommittee
        {
            public string name { get; set; }
            public string code { get; set; }
            public string parent_committee_id { get; set; }
            public string api_uri { get; set; }
            public string side { get; set; }
            public string title { get; set; }
            public int? rank_in_party { get; set; }
            public string begin_date { get; set; }
            public string end_date { get; set; }
        }
    }
    #endregion


}


