#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Write2Congress.Droid.Resource", IsApplication=true)]

namespace Write2Congress.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int accent_purple = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int primary_blue = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int primary_blue_dark = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_create_white_48dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_drafts_white_48dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_favorite_white_48dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_search_white_48dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_send_white_48dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000a
			public const int actionMenu_drafts = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int actionMenu_search = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int actionMenu_sent = 2131230731;
			
			// aapt resource value: 0x7f080009
			public const int actionMenu_writeNew = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int mainFrag_myButton = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int mainFrag_parent = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int mainFrag_result = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int mainFrag_zip = 2131230726;
			
			// aapt resource value: 0x7f080010
			public const int mainMenu_donate = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int mainMenu_exit = 2131230737;
			
			// aapt resource value: 0x7f08000d
			public const int mainMenu_search = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int mainMenu_settings = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int mainMenu_writeNew = 2131230734;
			
			// aapt resource value: 0x7f080003
			public const int main_bottomMenu = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int main_fragmentContainer = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int main_parent = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int main_toolbar = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int toolbar = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actv_Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ctrl_Toolbar = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int frag_Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int menu_action = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int menu_main = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int about = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int donate = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int drafts = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int exit = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int hello = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int searchLegislators = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int sent = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int settings = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int writeNew = 2131034120;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int MainMenuPopupTheme = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int ToolbarTheme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
